services:
  cloud.api:
    image: ${DOCKER_REGISTRY-}cloudapi
    build:
      context: .
      dockerfile: cloud.api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - cloud_data:/data/db

volumes:
  cloud_data:
  

